title: My first blog
description: >- # this means to ignore newlines until "email:"
  "This blog has been creatged during the mini-course 
  'Blogging with R' by Samantha Orlando on Sun March 24th, 2019"
email: samanthaorlando@msn.com

# Build settings
markdown: kramdown
exclude: ['*.Rmd'] # this is important to use with RMarkdown
theme: minima
plugins:
  - jekyll-feed # to serve posts